# Generated by Django 6.0.6 on 2026-06-27 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Championship',
                'verbose_name_plural': 'Championships',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_odds', models.FloatField(blank=True, null=True)),
                ('away_odds', models.FloatField(blank=True, null=True)),
                ('odds_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('match_date', models.DateTimeField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.championship')),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_corners', models.IntegerField(default=0)),
                ('away_corners', models.IntegerField(default=0)),
                ('home_yellow_cards', models.IntegerField(default=0)),
                ('away_yellow_cards', models.IntegerField(default=0)),
                ('home_red_cards', models.IntegerField(default=0)),
                ('away_red_cards', models.IntegerField(default=0)),
                ('home_shots', models.IntegerField(default=0)),
                ('away_shots', models.IntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.championship')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.round'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('future', 'Future'), ('active', 'Active'), ('finished', 'Finished')], default='active', max_length=20)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.championship')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.season'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.season'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.championship')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='core.team'),
        ),
        migrations.CreateModel(
            name='MatchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team'),
        ),
    ]
