# Generated by Django 6.0.6 on 2026-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('finished', 'Finished')], default='scheduled', max_length=20),
        ),
    ]
