# Generated by Django 6.0.6 on 2026-06-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='away_shots_on_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='home_shots_on_target',
            field=models.IntegerField(default=0),
        ),
    ]
