# Generated by Django 6.0.6 on 2026-06-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matchstats_away_shots_on_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='away_xg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='home_xg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
