# Generated by Django 6.0.6 on 2026-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
