# Generated by Django 6.0.6 on 2026-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_championship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
