MATCH_ODDS = [
    {
        "round": 1,
        "home": "Leeds United",
        "away": "Everton",
        "home_odds": 2.31,
        "away_odds": 3.34,
    },
    {
        "round": 1,
        "home": "Manchester United",
        "away": "Arsenal",
        "home_odds": 3.79,
        "away_odds": 1.99,
    },
    {
        "round": 1,
        "home": "Nottingham Forest",
        "away": "Brentford",
        "home_odds": 1.94,
        "away_odds": 4.28,
    },
    {
        "round": 1,
        "home": "Chelsea",
        "away": "Crystal Palace",
        "home_odds": 1.80,
        "away_odds": 4.66,
    },
    {
        "round": 1,
        "home": "Wolverhampton Wanderers",
        "away": "Manchester City",
        "home_odds": 6.70,
        "away_odds": 1.54,
    },
    {
        "round": 1,
        "home": "Brighton",
        "away": "Fulham",
        "home_odds": 1.84,
        "away_odds": 4.44,
    },
    {
        "round": 1,
        "home": "Sunderland",
        "away": "West Ham United",
        "home_odds": 3.57,
        "away_odds": 2.25,
    },
    {
        "round": 1,
        "home": "Tottenham Hotspur",
        "away": "Burnley",
        "home_odds": 1.60,
        "away_odds": 6.44,
    },
    {
        "round": 1,
        "home": "Aston Villa",
        "away": "Newcastle United",
        "home_odds": 2.44,
        "away_odds": 2.93,
    },
    {
        "round": 1,
        "home": "Liverpool",
        "away": "Bournemouth",
        "home_odds": 1.31,
        "away_odds": 9.15,
    },
    # ROUND 2
     {
        "round": 2,
        "home": "West Ham United",
        "away": "Chelsea",
        "home_odds": 4.86,
        "away_odds": 1.74,
    },
    {
        "round": 2,
        "home": "Manchester City",
        "away": "Tottenham Hotspur",
        "home_odds": 1.60,
        "away_odds": 5.43,
    },
    {
        "round": 2,
        "home": "Bournemouth",
        "away": "Wolverhampton Wanderers",
        "home_odds": 1.84,
        "away_odds": 4.44,
    },
    {
        "round": 2,
        "home": "Brentford",
        "away": "Aston Villa",
        "home_odds": 3.30,
        "away_odds": 2.26,
    },
    {
        "round": 2,
        "home": "Burnley",
        "away": "Sunderland",
        "home_odds": 2.40,
        "away_odds": 3.37,
    },
    {
        "round": 2,
        "home": "Crystal Palace",
        "away": "Nottingham Forest",
        "home_odds": 2.41,
        "away_odds": 3.17,
    },
    {
        "round": 2,
        "home": "Everton",
        "away": "Brighton",
        "home_odds": 2.95,
        "away_odds": 2.52,
    },
    {
        "round": 2,
        "home": "Fulham",
        "away": "Manchester United",
        "home_odds": 3.68,
        "away_odds": 2.04,
    },
    {
        "round": 2,
        "home": "Newcastle United",
        "away": "Liverpool",
        "home_odds": 3.10,
        "away_odds": 2.25,
    },
    {
        "round": 2,
        "home": "Arsenal",
        "away": "Leeds United",
        "home_odds": 1.36,
        "away_odds": 8.65,
    },
    # ROUND 3
    {
        "round": 3,
        "home": "Aston Villa",
        "away": "Crystal Palace",
        "home_odds": 2.13,
        "away_odds": 3.35,
    },
    {
        "round": 3,
        "home": "Chelsea",
        "away": "Fulham",
        "home_odds": 1.67,
        "away_odds": 5.18,
    },
    {
        "round": 3,
        "home": "Leeds United",
        "away": "Newcastle United",
        "home_odds": 4.14,
        "away_odds": 1.97,
    },
    {
        "round": 3,
        "home": "Liverpool",
        "away": "Arsenal",
        "home_odds": 2.43,
        "away_odds": 3.19,
    },
    {
        "round": 3,
        "home": "Manchester United",
        "away": "Burnley",
        "home_odds": 1.39,
        "away_odds": 7.55,
    },
    {
        "round": 3,
        "home": "Nottingham Forest",
        "away": "West Ham United",
        "home_odds": 1.68,
        "away_odds": 5.07,
    },
    {
        "round": 3,
        "home": "Sunderland",
        "away": "Brentford",
        "home_odds": 3.13,
        "away_odds": 2.37,
    },
    {
        "round": 3,
        "home": "Tottenham Hotspur",
        "away": "Bournemouth",
        "home_odds": 1.94,
        "away_odds": 3.81,
    },
    {
        "round": 3,
        "home": "Wolverhampton Wanderers",
        "away": "Everton",
        "home_odds": 3.43,
        "away_odds": 2.27,
    },
    {
        "round": 3,
        "home": "Brighton",
        "away": "Manchester City",
        "home_odds": 3.76,
        "away_odds": 2.00,
    },
    # ROUND 4
    {
        "round": 4,
        "home": "Arsenal",
        "away": "Nottingham Forest",
        "home_odds": 1.42,
        "away_odds": 7.62,
    },
    {
        "round": 4,
        "home": "Bournemouth",
        "away": "Brighton",
        "home_odds": 2.47,
        "away_odds": 2.83,
    },
    {
        "round": 4,
        "home": "Brentford",
        "away": "Chelsea",
        "home_odds": 4.61,
        "away_odds": 1.78,
    },
    {
        "round": 4,
        "home": "Burnley",
        "away": "Liverpool",
        "home_odds": 9.59,
        "away_odds": 1.30,
    },
    {
        "round": 4,
        "home": "Crystal Palace",
        "away": "Sunderland",
        "home_odds": 1.70,
        "away_odds": 5.59,
    },
    {
        "round": 4,
        "home": "Everton",
        "away": "Aston Villa",
        "home_odds": 2.72,
        "away_odds": 2.83,
    },
    {
        "round": 4,
        "home": "Fulham",
        "away": "Leeds United",
        "home_odds": 2.07,
        "away_odds": 3.74,
    },
    {
        "round": 4,
        "home": "Manchester City",
        "away": "Manchester United",
        "home_odds": 1.70,
        "away_odds": 4.58,
    },
    {
        "round": 4,
        "home": "Newcastle United",
        "away": "Wolverhampton Wanderers",
        "home_odds": 1.34,
        "away_odds": 9.09,
    },
    {
        "round": 4,
        "home": "West Ham United",
        "away": "Tottenham Hotspur",
        "home_odds": 3.48,
        "away_odds": 2.12,
    },
    # ROUND 5
     {
        "round": 5,
        "home": "Liverpool",
        "away": "Everton",
        "home_odds": 1.52,
        "away_odds": 6.75,
    },
    {
        "round": 5,
        "home": "Brighton",
        "away": "Tottenham Hotspur",
        "home_odds": 2.26,
        "away_odds": 3.15,
    },
    {
        "round": 5,
        "home": "Burnley",
        "away": "Nottingham Forest",
        "home_odds": 3.33,
        "away_odds": 2.30,
    },
    {
        "round": 5,
        "home": "West Ham United",
        "away": "Crystal Palace",
        "home_odds": 3.06,
        "away_odds": 2.40,
    },
    {
        "round": 5,
        "home": "Wolverhampton Wanderers",
        "away": "Leeds United",
        "home_odds": 3.05,
        "away_odds": 2.59,
    },
    {
        "round": 5,
        "home": "Manchester United",
        "away": "Chelsea",
        "home_odds": 2.78,
        "away_odds": 2.42,
    },
    {
        "round": 5,
        "home": "Fulham",
        "away": "Brentford",
        "home_odds": 2.17,
        "away_odds": 3.71,
    },
    {
        "round": 5,
        "home": "Bournemouth",
        "away": "Newcastle United",
        "home_odds": 2.59,
        "away_odds": 3.00,
    },
    {
        "round": 5,
        "home": "Sunderland",
        "away": "Aston Villa",
        "home_odds": 3.97,
        "away_odds": 2.04,
    },
    {
        "round": 5,
        "home": "Arsenal",
        "away": "Manchester City",
        "home_odds": 2.15,
        "away_odds": 3.40,
    },
    # ROUND 6
     {
        "round": 6,
        "home": "Aston Villa",
        "away": "Fulham",
        "home_odds": 2.25,
        "away_odds": 3.47,
    },
    {
        "round": 6,
        "home": "Brentford",
        "away": "Manchester United",
        "home_odds": 3.56,
        "away_odds": 2.04,
    },
    {
        "round": 6,
        "home": "Crystal Palace",
        "away": "Liverpool",
        "home_odds": 4.53,
        "away_odds": 1.86,
    },
    {
        "round": 6,
        "home": "Leeds United",
        "away": "Bournemouth",
        "home_odds": 3.06,
        "away_odds": 2.50,
    },
    {
        "round": 6,
        "home": "Manchester City",
        "away": "Burnley",
        "home_odds": 1.18,
        "away_odds": 16.10,
    },
    {
        "round": 6,
        "home": "Newcastle United",
        "away": "Arsenal",
        "home_odds": 3.61,
        "away_odds": 2.17,
    },
    {
        "round": 6,
        "home": "Nottingham Forest",
        "away": "Sunderland",
        "home_odds": 1.77,
        "away_odds": 4.81,
    },
    {
        "round": 6,
        "home": "Tottenham Hotspur",
        "away": "Wolverhampton Wanderers",
        "home_odds": 1.54,
        "away_odds": 6.67,
    },
    {
        "round": 6,
        "home": "Everton",
        "away": "West Ham United",
        "home_odds": 1.63,
        "away_odds": 6.00,
    },
    {
        "round": 6,
        "home": "Chelsea",
        "away": "Brighton",
        "home_odds": 1.98,
        "away_odds": 3.78,
    },
    # ROUND 7
    {
        "round": 7,
        "home": "Bournemouth",
        "away": "Fulham",
        "home_odds": 1.99,
        "away_odds": 4.18,
    },
    {
        "round": 7,
        "home": "Leeds United",
        "away": "Tottenham Hotspur",
        "home_odds": 2.90,
        "away_odds": 2.52,
    },
    {
        "round": 7,
        "home": "Arsenal",
        "away": "West Ham United",
        "home_odds": 1.19,
        "away_odds": 14.70,
    },
    {
        "round": 7,
        "home": "Manchester United",
        "away": "Sunderland",
        "home_odds": 1.66,
        "away_odds": 4.89,
    },
    {
        "round": 7,
        "home": "Chelsea",
        "away": "Liverpool",
        "home_odds": 3.09,
        "away_odds": 2.26,
    },
    {
        "round": 7,
        "home": "Everton",
        "away": "Crystal Palace",
        "home_odds": 2.66,
        "away_odds": 2.86,
    },
    {
        "round": 7,
        "home": "Aston Villa",
        "away": "Burnley",
        "home_odds": 1.57,
        "away_odds": 6.40,
    },
    {
        "round": 7,
        "home": "Newcastle United",
        "away": "Nottingham Forest",
        "home_odds": 1.54,
        "away_odds": 6.14,
    },
    {
        "round": 7,
        "home": "Wolverhampton Wanderers",
        "away": "Brighton",
        "home_odds": 3.57,
        "away_odds": 2.09,
    },
    {
        "round": 7,
        "home": "Brentford",
        "away": "Manchester City",
        "home_odds": 5.18,
        "away_odds": 1.64,
    },
    # ROUND 8
    {
        "round": 8,
        "home": "Nottingham Forest",
        "away": "Chelsea",
        "home_odds": 3.37,
        "away_odds": 2.20,
    },
    {
        "round": 8,
        "home": "Brighton",
        "away": "Newcastle United",
        "home_odds": 2.95,
        "away_odds": 2.42,
    },
    {
        "round": 8,
        "home": "Burnley",
        "away": "Leeds United",
        "home_odds": 3.52,
        "away_odds": 2.38,
    },
    {
        "round": 8,
        "home": "West Ham United",
        "away": "Brentford",
        "home_odds": 2.87,
        "away_odds": 2.62,
    },
    {
        "round": 8,
        "home": "Fulham",
        "away": "Arsenal",
        "home_odds": 6.98,
        "away_odds": 1.51,
    },
    {
        "round": 8,
        "home": "Liverpool",
        "away": "Manchester United",
        "home_odds": 1.68,
        "away_odds": 4.70,
    },
    {
        "round": 8,
        "home": "Crystal Palace",
        "away": "Bournemouth",
        "home_odds": 2.20,
        "away_odds": 3.58,
    },
    {
        "round": 8,
        "home": "Manchester City",
        "away": "Everton",
        "home_odds": 1.45,
        "away_odds": 8.68,
    },
    {
        "round": 8,
        "home": "Sunderland",
        "away": "Wolverhampton Wanderers",
        "home_odds": 2.58,
        "away_odds": 3.10,
    },
    {
        "round": 8,
        "home": "Tottenham Hotspur",
        "away": "Aston Villa",
        "home_odds": 2.15,
        "away_odds": 3.54,
    },
    # ROUND 9
    {
        "round": 9,
        "home": "Leeds United",
        "away": "West Ham United",
        "home_odds": 1.83,
        "away_odds": 4.57,
    },
    {
        "round": 9,
        "home": "Chelsea",
        "away": "Sunderland",
        "home_odds": 1.49,
        "away_odds": 7.16,
    },
    {
        "round": 9,
        "home": "Newcastle United",
        "away": "Fulham",
        "home_odds": 1.64,
        "away_odds": 5.57,
    },
    {
        "round": 9,
        "home": "Manchester United",
        "away": "Brighton",
        "home_odds": 1.97,
        "away_odds": 3.71,
    },
    {
        "round": 9,
        "home": "Brentford",
        "away": "Liverpool",
        "home_odds": 4.23,
        "away_odds": 1.82,
    },
    {
        "round": 9,
        "home": "Arsenal",
        "away": "Crystal Palace",
        "home_odds": 1.44,
        "away_odds": 7.18,
    },
    {
        "round": 9,
        "home": "Aston Villa",
        "away": "Manchester City",
        "home_odds": 4.50,
        "away_odds": 1.82,
    },
    {
        "round": 9,
        "home": "Bournemouth",
        "away": "Nottingham Forest",
        "home_odds": 1.94,
        "away_odds": 3.97,
    },
    {
        "round": 9,
        "home": "Wolverhampton Wanderers",
        "away": "Burnley",
        "home_odds": 1.96,
        "away_odds": 4.44,
    },
    {
        "round": 9,
        "home": "Everton",
        "away": "Tottenham Hotspur",
        "home_odds": 2.31,
        "away_odds": 3.15,
    },
    # ROUND 10
    {
        "round": 10,
        "home": "Fulham",
        "away": "Wolverhampton Wanderers",
        "home_odds": 1.83,
        "away_odds": 4.57,
    },
    {
        "round": 10,
        "home": "Burnley",
        "away": "Arsenal",
        "home_odds": 13.60,
        "away_odds": 1.25,
    },
    {
        "round": 10,
        "home": "Brighton",
        "away": "Leeds United",
        "home_odds": 1.96,
        "away_odds": 4.00,
    },
    {
        "round": 10,
        "home": "Nottingham Forest",
        "away": "Manchester United",
        "home_odds": 3.34,
        "away_odds": 2.12,
    },
    {
        "round": 10,
        "home": "Crystal Palace",
        "away": "Brentford",
        "home_odds": 2.12,
        "away_odds": 3.62,
    },
    {
        "round": 10,
        "home": "Liverpool",
        "away": "Aston Villa",
        "home_odds": 1.68,
        "away_odds": 4.68,
    },
    {
        "round": 10,
        "home": "Manchester City",
        "away": "Bournemouth",
        "home_odds": 1.46,
        "away_odds": 6.67,
    },
    {
        "round": 10,
        "home": "Sunderland",
        "away": "Everton",
        "home_odds": 3.26,
        "away_odds": 2.48,
    },
    {
        "round": 10,
        "home": "Tottenham Hotspur",
        "away": "Chelsea",
        "home_odds": 3.34,
        "away_odds": 2.22,
    },
    {
        "round": 10,
        "home": "West Ham United",
        "away": "Newcastle United",
        "home_odds": 4.86,
        "away_odds": 1.69,
    },
]