MATCH_STATS = [
    {
        "home": "Leeds United",
        "away": "Everton",
        "round": 1,
        "stats": {
            "home_corners": 7,
            "away_corners": 2,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 21,
            "away_shots": 7,
            "home_shots_on_target": 3,
            "away_shots_on_target": 1,
            "home_xg": 2.38,
            "away_xg": 0.67,
        },
        "goals": [
            {
                "team": "home",
                "minute": 84,
            },
        ],
    },
    {
        "home": "Manchester United",
        "away": "Arsenal",
        "round": 1,
        "stats": {
            "home_corners": 3,
            "away_corners": 4,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 22,
            "away_shots": 9,
            "home_shots_on_target": 7,
            "away_shots_on_target": 3,
            "home_xg": 1.38,
            "away_xg": 1.33,
        },
        "goals": [
            {
                "team": "away",
                "minute": 13,
            },
        ],
    },
    {
        "home": "Nottingham Forest",
        "away": "Brentford",
        "round": 1,
        "stats": {
            "home_corners": 5,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 11,
            "away_shots": 10,
            "home_shots_on_target": 5,
            "away_shots_on_target": 3,
            "home_xg": 1.76,
            "away_xg": 1.33,
        },
        "goals": [
            {
                "team": "home",
                "minute": 5,
            },
            {
                "team": "home",
                "minute": 42,
            },
            {
                "team": "home",
                "minute": 45,
            },
            {
                "team": "away",
                "minute": 78,
            },
        ],
    },
    {
        "home": "Chelsea",
        "away": "Crystal Palace",
        "round": 1,
        "stats": {
            "home_corners": 11,
            "away_corners": 2,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 19,
            "away_shots": 12,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 1.37,
            "away_xg": 1.03,
        },
        "goals": [],
    },
    {
        "home": "Wolverhampton Wanderers",
        "away": "Manchester City",
        "round": 1,
        "stats": {
            "home_corners": 4,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 15,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 0.47,
            "away_xg": 2.31,
        },
        "goals": [
            {
                "team": "away",
                "minute": 34,
            },
            {
                "team": "away",
                "minute": 37,
            },
            {
                "team": "away",
                "minute": 61,
            },
            {
                "team": "away",
                "minute": 81,
            },
        ],
    },
    {
        "home": "Brighton",
        "away": "Fulham",
        "round": 1,
        "stats": {
            "home_corners": 4,
            "away_corners": 3,
            "home_yellow_cards": 3,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 7,
            "home_shots_on_target": 4,
            "away_shots_on_target": 2,
            "home_xg": 1.44,
            "away_xg": 0.90,
        },
        "goals": [
            {
                "team": "home",
                "minute": 55,
            },
            {
                "team": "away",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Sunderland",
        "away": "West Ham United",
        "round": 1,
        "stats": {
            "home_corners": 5,
            "away_corners": 7,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 12,
            "home_shots_on_target": 5,
            "away_shots_on_target": 4,
            "home_xg": 0.72,
            "away_xg": 0.56,
        },
        "goals": [
            {
                "team": "home",
                "minute": 61,
            },
            {
                "team": "home",
                "minute": 73,
            },
            {
                "team": "home",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Tottenham Hotspur",
        "away": "Burnley",
        "round": 1,
        "stats": {
            "home_corners": 6,
            "away_corners": 5,
            "home_yellow_cards": 0,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 14,
            "home_shots_on_target": 6,
            "away_shots_on_target": 4,
            "home_xg": 1.98,
            "away_xg": 0.73,
        },
        "goals": [
            {
                "team": "home",
                "minute": 10,
            },
            {
                "team": "home",
                "minute": 60,
            },
            {
                "team": "home",
                "minute": 66,
            },
        ],
    },
    {
        "home": "Aston Villa",
        "away": "Newcastle United",
        "round": 1,
        "stats": {
            "home_corners": 3,
            "away_corners": 6,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 1,
            "away_red_cards": 0,
            "home_shots": 3,
            "away_shots": 16,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 0.32,
            "away_xg": 1.40,
        },
        "goals": [],
    },
    {
        "home": "Liverpool",
        "away": "Bournemouth",
        "round": 1,
        "stats": {
            "home_corners": 6,
            "away_corners": 7,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 19,
            "away_shots": 10,
            "home_shots_on_target": 10,
            "away_shots_on_target": 3,
            "home_xg": 2.38,
            "away_xg": 1.57,
        },
        "goals": [
            {
                "team": "home",
                "minute": 37,
            },
            {
                "team": "home",
                "minute": 49,
            },
            {
                "team": "away",
                "minute": 64,
            },
            {
                "team": "away",
                "minute": 76,
            },
            {
                "team": "away",
                "minute": 88,
            },
            {
                "team": "away",
                "minute": 90,
            },
        ],
    },
    # ROUND 2
    {
        "home": "West Ham United",
        "away": "Chelsea",
        "round": 2,
        "stats": {
            "home_corners": 7,
            "away_corners": 5,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 12,
            "home_shots_on_target": 4,
            "away_shots_on_target": 7,
            "home_xg": 0.98,
            "away_xg": 3.95,
        },
        "goals": [
            {
                "team": "away",
                "minute": 15,
            },
            {
                "team": "away",
                "minute": 23,
            },
            {
                "team": "away",
                "minute": 34,
            },
            {
                "team": "away",
                "minute": 54,
            },
            {
                "team": "away",
                "minute": 58,
            },
            {
                "team": "home",
                "minute": 6,
            },
        ],
    },
    {
        "home": "Manchester City",
        "away": "Tottenham Hotspur",
        "round": 2,
        "stats": {
            "home_corners": 7,
            "away_corners": 2,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 12,
            "home_shots_on_target": 4,
            "away_shots_on_target": 5,
            "home_xg": 1.25,
            "away_xg": 1.28,
        },
        "goals": [
            {
                "team": "away",
                "minute": 35,
            },
            {
                "team": "away",
                "minute": 45,
            },
        ],
    },
    {
        "home": "Bournemouth",
        "away": "Wolverhampton Wanderers",
        "round": 2,
        "stats": {
            "home_corners": 8,
            "away_corners": 3,
            "home_yellow_cards": 2,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 1,
            "home_shots": 14,
            "away_shots": 6,
            "home_shots_on_target": 4,
            "away_shots_on_target": 1,
            "home_xg": 1.78,
            "away_xg": 0.37,
        },
        "goals": [
            {
                "team": "home",
                "minute": 4,
            },
        ],
    },
    {
        "home": "Brentford",
        "away": "Aston Villa",
        "round": 2,
        "stats": {
            "home_corners": 2,
            "away_corners": 9,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 1,
            "home_shots": 9,
            "away_shots": 17,
            "home_shots_on_target": 2,
            "away_shots_on_target": 2,
            "home_xg": 1.13,
            "away_xg": 0.98,
        },
        "goals": [
            {
                "team": "home",
                "minute": 12,
            },
        ],
    },
    {
        "home": "Burnley",
        "away": "Sunderland",
        "round": 2,
        "stats": {
            "home_corners": 4,
            "away_corners": 3,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 7,
            "away_shots": 9,
            "home_shots_on_target": 2,
            "away_shots_on_target": 1,
            "home_xg": 1.00,
            "away_xg": 1.12,
        },
        "goals": [
            {
                "team": "home",
                "minute": 47,
            },
            {
                "team": "home",
                "minute": 88,
            },
        ],
    },
    {
        "home": "Crystal Palace",
        "away": "Nottingham Forest",
        "round": 2,
        "stats": {
            "home_corners": 1,
            "away_corners": 3,
            "home_yellow_cards": 3,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 8,
            "away_shots": 9,
            "home_shots_on_target": 4,
            "away_shots_on_target": 1,
            "home_xg": 1.10,
            "away_xg": 1.33,
        },
        "goals": [
            {
                "team": "home",
                "minute": 37,
            },
            {
                "team": "away",
                "minute": 57,
            },
        ],
    },
    {
        "home": "Everton",
        "away": "Brighton",
        "round": 2,
        "stats": {
            "home_corners": 2,
            "away_corners": 2,
            "home_yellow_cards": 4,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 11,
            "away_shots": 13,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 1.80,
            "away_xg": 2.08,
        },
        "goals": [
            {
                "team": "home",
                "minute": 23,
            },
            {
                "team": "home",
                "minute": 52,
            },
        ],
    },
    {
        "home": "Fulham",
        "away": "Manchester United",
        "round": 2,
        "stats": {
            "home_corners": 9,
            "away_corners": 6,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 10,
            "home_shots_on_target": 4,
            "away_shots_on_target": 3,
            "home_xg": 1.65,
            "away_xg": 1.55,
        },
        "goals": [
            {
                "team": "home",
                "minute": 73,
            },
            {
                "team": "away",
                "minute": 58,
            },
        ],
    },
    {
        "home": "Newcastle United",
        "away": "Liverpool",
        "round": 2,
        "stats": {
            "home_corners": 7,
            "away_corners": 1,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 1,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 5,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 1.96,
            "away_xg": 0.65,
        },
        "goals": [
            {
                "team": "home",
                "minute": 57,
            },
            {
                "team": "home",
                "minute": 88,
            },
            {
                "team": "away",
                "minute": 58,
            },
            {
                "team": "away",
                "minute": 46,
            },
            {
                "team": "away",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Arsenal",
        "away": "Leeds United",
        "round": 2,
        "stats": {
            "home_corners": 2,
            "away_corners": 2,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 18,
            "away_shots": 3,
            "home_shots_on_target": 5,
            "away_shots_on_target": 1,
            "home_xg": 2.74,
            "away_xg": 0.16,
        },
        "goals": [
            {
                "team": "home",
                "minute": 34,
            },
            {
                "team": "home",
                "minute": 45,
            },
            {
                "team": "home",
                "minute": 48,
            },
            {
                "team": "home",
                "minute": 56,
            },
            {
                "team": "home",
                "minute": 90,
            },
        ],
    },
    # ROUND 3
    {
        "home": "Aston Villa",
        "away": "Crystal Palace",
        "round": 3,
        "stats": {
            "home_corners": 10,
            "away_corners": 1,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 6,
            "home_shots_on_target": 4,
            "away_shots_on_target": 4,
            "home_xg": 1.21,
            "away_xg": 2.60,
        },
        "goals": [
            {
                "team": "away",
                "minute": 21,
            },
            {
                "team": "away",
                "minute": 68,
            },
            {
                "team": "away",
                "minute": 78,
            },
        ],
    },
    {
        "home": "Chelsea",
        "away": "Fulham",
        "round": 3,
        "stats": {
            "home_corners": 6,
            "away_corners": 4,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 11,
            "home_shots_on_target": 6,
            "away_shots_on_target": 3,
            "home_xg": 2.43,
            "away_xg": 0.74,
        },
        "goals": [
            {
                "team": "home",
                "minute": 45,
            },
            {
                "team": "home",
                "minute": 56,
            },
        ],
    },
    {
        "home": "Leeds United",
        "away": "Newcastle United",
        "round": 3,
        "stats": {
            "home_corners": 5,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 8,
            "home_shots_on_target": 1,
            "away_shots_on_target": 2,
            "home_xg": 0.68,
            "away_xg": 0.30,
        },
        "goals": [],
    },
    {
        "home": "Liverpool",
        "away": "Arsenal",
        "round": 3,
        "stats": {
            "home_corners": 3,
            "away_corners": 8,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 11,
            "home_shots_on_target": 3,
            "away_shots_on_target": 1,
            "home_xg": 0.48,
            "away_xg": 0.49,
        },
        "goals": [
            {
                "team": "home",
                "minute": 83,
            },
        ],
    },
    {
        "home": "Manchester United",
        "away": "Burnley",
        "round": 3,
        "stats": {
            "home_corners": 7,
            "away_corners": 1,
            "home_yellow_cards": 1,
            "away_yellow_cards": 5,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 26,
            "away_shots": 6,
            "home_shots_on_target": 6,
            "away_shots_on_target": 3,
            "home_xg": 4.02,
            "away_xg": 1.33,
        },
        "goals": [
            {
                "team": "home",
                "minute": 27,
            },
            {
                "team": "home",
                "minute": 57,
            },
            {
                "team": "home",
                "minute": 90,
            },
            {
                "team": "away",
                "minute": 55,
            },
            {
                "team": "away",
                "minute": 66,
            },
        ],
    },
    {
        "home": "Nottingham Forest",
        "away": "West Ham United",
        "round": 3,
        "stats": {
            "home_corners": 9,
            "away_corners": 7,
            "home_yellow_cards": 0,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 11,
            "away_shots": 12,
            "home_shots_on_target": 3,
            "away_shots_on_target": 8,
            "home_xg": 0.72,
            "away_xg": 2.24,
        },
        "goals": [
            {
                "team": "away",
                "minute": 84,
            },
            {
                "team": "away",
                "minute": 88,
            },
            {
                "team": "away",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Sunderland",
        "away": "Brentford",
        "round": 3,
        "stats": {
            "home_corners": 3,
            "away_corners": 4,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 7,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 1.57,
            "away_xg": 1.45,
        },
        "goals": [
            {
                "team": "away",
                "minute": 77,
            },
            {
                "team": "home",
                "minute": 82,
            },
            {
                "team": "home",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Tottenham Hotspur",
        "away": "Bournemouth",
        "round": 3,
        "stats": {
            "home_corners": 0,
            "away_corners": 8,
            "home_yellow_cards": 2,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 5,
            "away_shots": 19,
            "home_shots_on_target": 1,
            "away_shots_on_target": 6,
            "home_xg": 0.17,
            "away_xg": 2.12,
        },
        "goals": [
            {
                "team": "away",
                "minute": 5,
            },
        ],
    },
    {
        "home": "Wolverhampton Wanderers",
        "away": "Everton",
        "round": 3,
        "stats": {
            "home_corners": 2,
            "away_corners": 2,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 10,
            "home_shots_on_target": 4,
            "away_shots_on_target": 4,
            "home_xg": 0.94,
            "away_xg": 2.04,
        },
        "goals": [
            {
                "team": "away",
                "minute": 7,
            },
            {
                "team": "home",
                "minute": 21,
            },
            {
                "team": "home",
                "minute": 33,
            },
            {
                "team": "home",
                "minute": 55,
            },
            {
                "team": "away",
                "minute": 79,
            },
        ],
    },
    {
        "home": "Brighton",
        "away": "Manchester City",
        "round": 3,
        "stats": {
            "home_corners": 3,
            "away_corners": 2,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 12,
            "home_shots_on_target": 7,
            "away_shots_on_target": 3,
            "home_xg": 2.21,
            "away_xg": 2.13,
        },
        "goals": [
            {
                "team": "home",
                "minute": 67,
            },
            {
                "team": "home",
                "minute": 89,
            },
            {
                "team": "away",
                "minute": 34,
            },
        ],
    },
    # ROUND 4
    {
        "home": "Arsenal",
        "away": "Nottingham Forest",
        "round": 4,
        "stats": {
            "home_corners": 8,
            "away_corners": 3,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 5,
            "home_shots_on_target": 5,
            "away_shots_on_target": 1,
            "home_xg": 2.88,
            "away_xg": 0.29,
        },
        "goals": [
            {
                "team": "home",
                "minute": 32,
            },
            {
                "team": "home",
                "minute": 46,
            },
            {
                "team": "home",
                "minute": 79,
            },
        ],
    },
    {
        "home": "Bournemouth",
        "away": "Brighton",
        "round": 4,
        "stats": {
            "home_corners": 4,
            "away_corners": 4,
            "home_yellow_cards": 4,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 6,
            "home_shots_on_target": 5,
            "away_shots_on_target": 2,
            "home_xg": 1.44,
            "away_xg": 0.62,
        },
        "goals": [
            {
                "team": "home",
                "minute": 18,
            },
            {
                "team": "home",
                "minute": 61,
            },
            {
                "team": "away",
                "minute": 48,
            },
        ],
    },
    {
        "home": "Brentford",
        "away": "Chelsea",
        "round": 4,
        "stats": {
            "home_corners": 5,
            "away_corners": 6,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 7,
            "away_shots": 16,
            "home_shots_on_target": 4,
            "away_shots_on_target": 6,
            "home_xg": 1.18,
            "away_xg": 0.76,
        },
        "goals": [
            {
                "team": "home",
                "minute": 35,
            },
            {
                "team": "away",
                "minute": 61,
            },
            {
                "team": "home",
                "minute": 90,
            },
            {
                "team": "away",
                "minute": 85,
            },
        ],
    },
    {
        "home": "Burnley",
        "away": "Liverpool",
        "round": 4,
        "stats": {
            "home_corners": 1,
            "away_corners": 13,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 1,
            "away_red_cards": 0,
            "home_shots": 3,
            "away_shots": 27,
            "home_shots_on_target": 0,
            "away_shots_on_target": 4,
            "home_xg": 0.17,
            "away_xg": 2.79,
        },
        "goals": [
            {
                "team": "away",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Crystal Palace",
        "away": "Sunderland",
        "round": 4,
        "stats": {
            "home_corners": 5,
            "away_corners": 3,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 14,
            "away_shots": 6,
            "home_shots_on_target": 6,
            "away_shots_on_target": 0,
            "home_xg": 1.76,
            "away_xg": 0.35,
        },
        "goals": [],
    },
    {
        "home": "Everton",
        "away": "Aston Villa",
        "round": 4,
        "stats": {
            "home_corners": 10,
            "away_corners": 3,
            "home_yellow_cards": 3,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 20,
            "away_shots": 6,
            "home_shots_on_target": 2,
            "away_shots_on_target": 1,
            "home_xg": 1.89,
            "away_xg": 0.35,
        },
        "goals": [],
    },
    {
        "home": "Fulham",
        "away": "Leeds United",
        "round": 4,
        "stats": {
            "home_corners": 3,
            "away_corners": 3,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 5,
            "away_red_cards": 10,
            "home_shots": 3,
            "away_shots": 2,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 1.14,
            "away_xg": 0.83,
        },
        "goals": [
            {
                "team": "home",
                "minute": 90,
            },
        ],
    },
    {
        "home": "Manchester City",
        "away": "Manchester United",
        "round": 4,
        "stats": {
            "home_corners": 2,
            "away_corners": 4,
            "home_yellow_cards": 0,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 12,
            "home_shots_on_target": 6,
            "away_shots_on_target": 2,
            "home_xg": 2.00,
            "away_xg": 1.52,
        },
        "goals": [
            {
                "team": "home",
                "minute": 18,
            },
            {
                "team": "home",
                "minute": 53,
            },
            {
                "team": "home",
                "minute": 68,
            },
        ],
    },
    {
        "home": "Newcastle United",
        "away": "Wolverhampton Wanderers",
        "round": 4,
        "stats": {
            "home_corners": 7,
            "away_corners": 3,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 6,
            "home_shots_on_target": 4,
            "away_shots_on_target": 3,
            "home_xg": 1.19,
            "away_xg": 0.38,
        },
        "goals": [
            {
                "team": "home",
                "minute": 29,
            },
        ],
    },
    {
        "home": "West Ham United",
        "away": "Tottenham Hotspur",
        "round": 4,
        "stats": {
            "home_corners": 2,
            "away_corners": 13,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 1,
            "away_red_cards": 0,
            "home_shots": 7,
            "away_shots": 14,
            "home_shots_on_target": 4,
            "away_shots_on_target": 5,
            "home_xg": 0.79,
            "away_xg": 1.51,
        },
        "goals": [
            {
                "team": "away",
                "minute": 47,
            },
            {
                "team": "away",
                "minute": 57,
            },
            {
                "team": "away",
                "minute": 64,
            },
        ],
    },
    # ROUND 5
    {
        "home": "Liverpool",
        "away": "Everton",
        "round": 5,
        "stats": {
            "home_corners": 5,
            "away_corners": 4,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 11,
            "away_shots": 9,
            "home_shots_on_target": 3,
            "away_shots_on_target": 2,
            "home_xg": 1.06,
            "away_xg": 0.72,
        },
        "goals": [
            {"team": "home", "minute": 10},
            {"team": "home", "minute": 29},
            {"team": "away", "minute": 58},
        ],
    },
    {
        "home": "Brighton",
        "away": "Tottenham Hotspur",
        "round": 5,
        "stats": {
            "home_corners": 2,
            "away_corners": 10,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 11,
            "home_shots_on_target": 4,
            "away_shots_on_target": 3,
            "home_xg": 1.40,
            "away_xg": 1.19,
        },
        "goals": [
            {"team": "home", "minute": 8},
            {"team": "home", "minute": 31},
            {"team": "away", "minute": 43},
            {"team": "away", "minute": 82},
        ],
    },
    {
        "home": "Burnley",
        "away": "Nottingham Forest",
        "round": 5,
        "stats": {
            "home_corners": 4,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 17,
            "home_shots_on_target": 5,
            "away_shots_on_target": 8,
            "home_xg": 1.14,
            "away_xg": 0.83,
        },
        "goals": [{"team": "home", "minute": 2}, {"team": "away", "minute": 20}],
    },
    {
        "home": "West Ham United",
        "away": "Crystal Palace",
        "round": 5,
        "stats": {
            "home_corners": 8,
            "away_corners": 8,
            "home_yellow_cards": 3,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 8,
            "away_shots": 18,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 0.47,
            "away_xg": 2.34,
        },
        "goals": [
            {"team": "home", "minute": 49},
            {"team": "away", "minute": 37},
            {"team": "away", "minute": 68},
        ],
    },
    {
        "home": "Wolverhampton Wanderers",
        "away": "Leeds United",
        "round": 5,
        "stats": {
            "home_corners": 4,
            "away_corners": 0,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 6,
            "home_shots_on_target": 6,
            "away_shots_on_target": 4,
            "home_xg": 1.57,
            "away_xg": 0.46,
        },
        "goals": [
            {"team": "home", "minute": 8},
            {"team": "away", "minute": 31},
            {"team": "away", "minute": 39},
            {"team": "away", "minute": 45},
        ],
    },
    {
        "home": "Manchester United",
        "away": "Chelsea",
        "round": 5,
        "stats": {
            "home_corners": 5,
            "away_corners": 5,
            "home_yellow_cards": 2,
            "away_yellow_cards": 5,
            "home_red_cards": 1,
            "away_red_cards": 1,
            "home_shots": 11,
            "away_shots": 5,
            "home_shots_on_target": 4,
            "away_shots_on_target": 1,
            "home_xg": 1.34,
            "away_xg": 0.47,
        },
        "goals": [
            {"team": "home", "minute": 14},
            {"team": "home", "minute": 37},
            {"team": "away", "minute": 80},
        ],
    },
    {
        "home": "Fulham",
        "away": "Brentford",
        "round": 5,
        "stats": {
            "home_corners": 2,
            "away_corners": 10,
            "home_yellow_cards": 4,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 14,
            "away_shots": 8,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 1.52,
            "away_xg": 0.83,
        },
        "goals": [
            {"team": "home", "minute": 38},
            {"team": "home", "minute": 40},
            {"team": "home", "minute": 50},
            {"team": "away", "minute": 20},
        ],
    },
    {
        "home": "Bournemouth",
        "away": "Newcastle United",
        "round": 5,
        "stats": {
            "home_corners": 5,
            "away_corners": 2,
            "home_yellow_cards": 2,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 11,
            "away_shots": 4,
            "home_shots_on_target": 2,
            "away_shots_on_target": 1,
            "home_xg": 0.55,
            "away_xg": 0.15,
        },
        "goals": [],
    },
    {
        "home": "Sunderland",
        "away": "Aston Villa",
        "round": 5,
        "stats": {
            "home_corners": 6,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 1,
            "away_red_cards": 0,
            "home_shots": 14,
            "away_shots": 12,
            "home_shots_on_target": 4,
            "away_shots_on_target": 2,
            "home_xg": 0.94,
            "away_xg": 0.94,
        },
        "goals": [{"team": "home", "minute": 75}, {"team": "away", "minute": 67}],
    },
    {
        "home": "Arsenal",
        "away": "Manchester City",
        "round": 5,
        "stats": {
            "home_corners": 11,
            "away_corners": 1,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 5,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 0.72,
            "away_xg": 1.12,
        },
        "goals": [{"team": "home", "minute": 90}, {"team": "away", "minute": 9}],
    },
    # Round 6
    {
        "home": "Aston Villa",
        "away": "Fulham",
        "round": 6,
        "stats": {
            "home_corners": 2,
            "away_corners": 8,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 11,
            "home_shots_on_target": 4,
            "away_shots_on_target": 4,
            "home_xg": 1.37,
            "away_xg": 0.95,
        },
        "goals": [
            {"team": "home", "minute": 37},
            {"team": "home", "minute": 49},
            {"team": "home", "minute": 51},
            {"team": "away", "minute": 3},
        ],
    },
    {
        "home": "Brentford",
        "away": "Manchester United",
        "round": 6,
        "stats": {
            "home_corners": 4,
            "away_corners": 2,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 14,
            "home_shots_on_target": 8,
            "away_shots_on_target": 6,
            "home_xg": 2.79,
            "away_xg": 2.24,
        },
        "goals": [
            {"team": "home", "minute": 8},
            {"team": "home", "minute": 20},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 26},
        ],
    },
    {
        "home": "Crystal Palace",
        "away": "Liverpool",
        "round": 6,
        "stats": {
            "home_corners": 2,
            "away_corners": 6,
            "home_yellow_cards": 1,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 20,
            "home_shots_on_target": 7,
            "away_shots_on_target": 4,
            "home_xg": 3.53,
            "away_xg": 3.1,
        },
        "goals": [
            {"team": "home", "minute": 9},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 87},
        ],
    },
    {
        "home": "Leeds United",
        "away": "Bournemouth",
        "round": 6,
        "stats": {
            "home_corners": 7,
            "away_corners": 4,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 19,
            "away_shots": 12,
            "home_shots_on_target": 8,
            "away_shots_on_target": 5,
            "home_xg": 2.05,
            "away_xg": 1.06,
        },
        "goals": [
            {"team": "home", "minute": 37},
            {"team": "home", "minute": 54},
            {"team": "away", "minute": 26},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Manchester City",
        "away": "Burnley",
        "round": 6,
        "stats": {
            "home_corners": 10,
            "away_corners": 2,
            "home_yellow_cards": 1,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 21,
            "away_shots": 9,
            "home_shots_on_target": 8,
            "away_shots_on_target": 2,
            "home_xg": 3.22,
            "away_xg": 0.51,
        },
        "goals": [
            {"team": "home", "minute": 12},
            {"team": "home", "minute": 61},
            {"team": "home", "minute": 65},
            {"team": "home", "minute": 90},
            {"team": "home", "minute": 91},
            {"team": "away", "minute": 38},
        ],
    },
    {
        "home": "Newcastle United",
        "away": "Arsenal",
        "round": 6,
        "stats": {
            "home_corners": 7,
            "away_corners": 12,
            "home_yellow_cards": 2,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 8,
            "away_shots": 20,
            "home_shots_on_target": 3,
            "away_shots_on_target": 7,
            "home_xg": 0.74,
            "away_xg": 2.07,
        },
        "goals": [
            {"team": "home", "minute": 34},
            {"team": "away", "minute": 84},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Nottingham Forest",
        "away": "Sunderland",
        "round": 6,
        "stats": {
            "home_corners": 7,
            "away_corners": 4,
            "home_yellow_cards": 4,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 22,
            "away_shots": 11,
            "home_shots_on_target": 6,
            "away_shots_on_target": 3,
            "home_xg": 1.42,
            "away_xg": 1.94,
        },
        "goals": [
            {"team": "away", "minute": 38},
        ],
    },
    {
        "home": "Tottenham Hotspur",
        "away": "Wolverhampton Wanderers",
        "round": 6,
        "stats": {
            "home_corners": 10,
            "away_corners": 9,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 9,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 0.82,
            "away_xg": 1.16,
        },
        "goals": [
            {"team": "home", "minute": 54},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Everton",
        "away": "West Ham United",
        "round": 6,
        "stats": {
            "home_corners": 3,
            "away_corners": 5,
            "home_yellow_cards": 3,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 14,
            "home_shots_on_target": 6,
            "away_shots_on_target": 3,
            "home_xg": 0.74,
            "away_xg": 1.17,
        },
        "goals": [
            {"team": "home", "minute": 18},
            {"team": "away", "minute": 65},
        ],
    },
    {
        "home": "Chelsea",
        "away": "Brighton",
        "round": 6,
        "stats": {
            "home_corners": 5,
            "away_corners": 7,
            "home_yellow_cards": 4,
            "away_yellow_cards": 5,
            "home_red_cards": 1,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 12,
            "home_shots_on_target": 3,
            "away_shots_on_target": 3,
            "home_xg": 2.03,
            "away_xg": 2.48,
        },
        "goals": [
            {"team": "home", "minute": 24},
            {"team": "away", "minute": 77},
            {"team": "away", "minute": 90},
            {"team": "away", "minute": 91},
        ],
    },
    # ROUND 7
    {
        "home": "Bournemouth",
        "away": "Fulham",
        "round": 7,
        "stats": {
            "home_corners": 4,
            "away_corners": 3,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 11,
            "away_shots": 12,
            "home_shots_on_target": 6,
            "away_shots_on_target": 4,
            "home_xg": 1.33,
            "away_xg": 0.84,
        },
        "goals": [
            {"team": "home", "minute": 78},
            {"team": "home", "minute": 84},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 70},
        ],
    },
    {
        "home": "Leeds United",
        "away": "Tottenham Hotspur",
        "round": 7,
        "stats": {
            "home_corners": 4,
            "away_corners": 1,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 9,
            "home_shots_on_target": 4,
            "away_shots_on_target": 3,
            "home_xg": 1.48,
            "away_xg": 0.69,
        },
        "goals": [
            {"team": "home", "minute": 34},
            {"team": "away", "minute": 23},
            {"team": "away", "minute": 57},
        ],
    },
    {
        "home": "Arsenal",
        "away": "West Ham United",
        "round": 7,
        "stats": {
            "home_corners": 8,
            "away_corners": 3,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 21,
            "away_shots": 4,
            "home_shots_on_target": 5,
            "away_shots_on_target": 0,
            "home_xg": 3.06,
            "away_xg": 0.86,
        },
        "goals": [
            {"team": "home", "minute": 38},
            {"team": "home", "minute": 67},
        ],
    },
    {
        "home": "Manchester United",
        "away": "Sunderland",
        "round": 7,
        "stats": {
            "home_corners": 2,
            "away_corners": 3,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 15,
            "away_shots": 8,
            "home_shots_on_target": 6,
            "away_shots_on_target": 3,
            "home_xg": 1.93,
            "away_xg": 0.81,
        },
        "goals": [
            {"team": "home", "minute": 8},
            {"team": "home", "minute": 31},
        ],
    },
    {
        "home": "Chelsea",
        "away": "Liverpool",
        "round": 7,
        "stats": {
            "home_corners": 7,
            "away_corners": 2,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 12,
            "home_shots_on_target": 6,
            "away_shots_on_target": 2,
            "home_xg": 1.24,
            "away_xg": 2.06,
        },
        "goals": [
            {"team": "home", "minute": 14},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 63},
        ],
    },
    {
        "home": "Everton",
        "away": "Crystal Palace",
        "round": 7,
        "stats": {
            "home_corners": 2,
            "away_corners": 4,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 14,
            "away_shots": 15,
            "home_shots_on_target": 7,
            "away_shots_on_target": 8,
            "home_xg": 2.14,
            "away_xg": 2.18,
        },
        "goals": [
            {"team": "home", "minute": 76},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 37},
        ],
    },
    {
        "home": "Aston Villa",
        "away": "Burnley",
        "round": 7,
        "stats": {
            "home_corners": 6,
            "away_corners": 4,
            "home_yellow_cards": 3,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 15,
            "away_shots": 5,
            "home_shots_on_target": 7,
            "away_shots_on_target": 2,
            "home_xg": 1.74,
            "away_xg": 0.5,
        },
        "goals": [
            {"team": "home", "minute": 25},
            {"team": "home", "minute": 63},
            {"team": "away", "minute": 78},
        ],
    },
    {
        "home": "Newcastle United",
        "away": "Nottingham Forest",
        "round": 7,
        "stats": {
            "home_corners": 8,
            "away_corners": 1,
            "home_yellow_cards": 0,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 18,
            "away_shots": 5,
            "home_shots_on_target": 9,
            "away_shots_on_target": 4,
            "home_xg": 3.82,
            "away_xg": 0.34,
        },
        "goals": [
            {"team": "home", "minute": 58},
            {"team": "home", "minute": 84},
        ],
    },
    {
        "home": "Wolverhampton Wanderers",
        "away": "Brighton",
        "round": 7,
        "stats": {
            "home_corners": 2,
            "away_corners": 8,
            "home_yellow_cards": 2,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 6,
            "away_shots": 17,
            "home_shots_on_target": 3,
            "away_shots_on_target": 6,
            "home_xg": 0.37,
            "away_xg": 1.39,
        },
        "goals": [
            {"team": "home", "minute": 21},
            {"team": "away", "minute": 86},
        ],
    },
    {
        "home": "Brentford",
        "away": "Manchester City",
        "round": 7,
        "stats": {
            "home_corners": 3,
            "away_corners": 2,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 6,
            "away_shots": 10,
            "home_shots_on_target": 1,
            "away_shots_on_target": 4,
            "home_xg": 0.69,
            "away_xg": 1.10,
        },
        "goals": [
            {"team": "away", "minute": 9},
        ],
    },
    # ROUND 8
    {
        "home": "Nottingham Forest",
        "away": "Chelsea",
        "round": 8,
        "stats": {
            "home_corners": 5,
            "away_corners": 2,
            "home_yellow_cards": 2,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 1,
            "home_shots": 12,
            "away_shots": 17,
            "home_shots_on_target": 2,
            "away_shots_on_target": 6,
            "home_xg": 2.06,
            "away_xg": 2.56,
        },
        "goals": [
            {"team": "away", "minute": 49},
            {"team": "away", "minute": 52},
            {"team": "away", "minute": 84},
        ],
    },
    {
        "home": "Brighton",
        "away": "Newcastle United",
        "round": 8,
        "stats": {
            "home_corners": 8,
            "away_corners": 4,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 16,
            "home_shots_on_target": 5,
            "away_shots_on_target": 3,
            "home_xg": 0.86,
            "away_xg": 1.28,
        },
        "goals": [
            {"team": "home", "minute": 41},
            {"team": "home", "minute": 84},
            {"team": "away", "minute": 76},
        ],
    },
    {
        "home": "Burnley",
        "away": "Leeds United",
        "round": 8,
        "stats": {
            "home_corners": 1,
            "away_corners": 5,
            "home_yellow_cards": 2,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 4,
            "away_shots": 19,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 0.51,
            "away_xg": 2.33,
        },
        "goals": [
            {"team": "home", "minute": 18},
            {"team": "home", "minute": 68},
        ],
    },
    {
        "home": "West Ham United",
        "away": "Brentford",
        "round": 8,
        "stats": {
            "home_corners": 0,
            "away_corners": 0,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 7,
            "away_shots": 22,
            "home_shots_on_target": 1,
            "away_shots_on_target": 7,
            "home_xg": 0.26,
            "away_xg": 3.47,
        },
        "goals": [{"team": "away", "minute": 43}, {"team": "away", "minute": 90}],
    },
    {
        "home": "Fulham",
        "away": "Arsenal",
        "round": 8,
        "stats": {
            "home_corners": 6,
            "away_corners": 10,
            "home_yellow_cards": 0,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 16,
            "home_shots_on_target": 0,
            "away_shots_on_target": 5,
            "home_xg": 0.5,
            "away_xg": 2.08,
        },
        "goals": [{"team": "away", "minute": 58}],
    },
    {
        "home": "Liverpool",
        "away": "Manchester United",
        "round": 8,
        "stats": {
            "home_corners": 9,
            "away_corners": 4,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 19,
            "away_shots": 12,
            "home_shots_on_target": 6,
            "away_shots_on_target": 4,
            "home_xg": 2.61,
            "away_xg": 2.53,
        },
        "goals": [
            {"team": "home", "minute": 78},
            {"team": "away", "minute": 2},
            {"team": "away", "minute": 84},
        ],
    },
    {
        "home": "Crystal Palace",
        "away": "Bournemouth",
        "round": 8,
        "stats": {
            "home_corners": 6,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 20,
            "away_shots": 9,
            "home_shots_on_target": 7,
            "away_shots_on_target": 5,
            "home_xg": 4.56,
            "away_xg": 2.05,
        },
        "goals": [
            {"team": "home", "minute": 64},
            {"team": "home", "minute": 69},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 7},
            {"team": "away", "minute": 38},
            {"team": "away", "minute": 89},
        ],
    },
    {
        "home": "Manchester City",
        "away": "Everton",
        "round": 8,
        "stats": {
            "home_corners": 11,
            "away_corners": 3,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 19,
            "away_shots": 5,
            "home_shots_on_target": 7,
            "away_shots_on_target": 1,
            "home_xg": 2.48,
            "away_xg": 0.79,
        },
        "goals": [{"team": "home", "minute": 58}, {"team": "home", "minute": 63}],
    },
    {
        "home": "Sunderland",
        "away": "Wolverhampton Wanderers",
        "round": 8,
        "stats": {
            "home_corners": 2,
            "away_corners": 2,
            "home_yellow_cards": 0,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 8,
            "away_shots": 16,
            "home_shots_on_target": 2,
            "away_shots_on_target": 3,
            "home_xg": 1.02,
            "away_xg": 0.68,
        },
        "goals": [
            {"team": "home", "minute": 16},
            {"team": "home", "minute": 90},
        ],
    },
    {
        "home": "Tottenham Hotspur",
        "away": "Aston Villa",
        "round": 8,
        "stats": {
            "home_corners": 6,
            "away_corners": 6,
            "home_yellow_cards": 2,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 8,
            "home_shots_on_target": 3,
            "away_shots_on_target": 2,
            "home_xg": 1.51,
            "away_xg": 0.35,
        },
        "goals": [
            {"team": "home", "minute": 5},
            {"team": "away", "minute": 37},
            {"team": "away", "minute": 77},
        ],
    },
    # ROUND 9
    {
        "home": "Leeds United",
        "away": "West Ham United",
        "round": 9,
        "stats": {
            "home_corners": 3,
            "away_corners": 4,
            "home_yellow_cards": 3,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 9,
            "home_shots_on_target": 5,
            "away_shots_on_target": 3,
            "home_xg": 2.22,
            "away_xg": 0.5,
        },
        "goals": [
            {"team": "home", "minute": 3},
            {"team": "home", "minute": 15},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Chelsea",
        "away": "Sunderland",
        "round": 9,
        "stats": {
            "home_corners": 9,
            "away_corners": 1,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 10,
            "home_shots_on_target": 7,
            "away_shots_on_target": 4,
            "home_xg": 1.21,
            "away_xg": 1.55,
        },
        "goals": [
            {"team": "home", "minute": 4},
            {"team": "away", "minute": 22},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Newcastle United",
        "away": "Fulham",
        "round": 9,
        "stats": {
            "home_corners": 4,
            "away_corners": 3,
            "home_yellow_cards": 0,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 18,
            "away_shots": 12,
            "home_shots_on_target": 7,
            "away_shots_on_target": 5,
            "home_xg": 2.77,
            "away_xg": 1.52,
        },
        "goals": [
            {"team": "home", "minute": 18},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 56},
        ],
    },
    {
        "home": "Manchester United",
        "away": "Brighton",
        "round": 9,
        "stats": {
            "home_corners": 1,
            "away_corners": 6,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 17,
            "home_shots_on_target": 9,
            "away_shots_on_target": 5,
            "home_xg": 1.96,
            "away_xg": 0.95,
        },
        "goals": [
            {"team": "home", "minute": 24},
            {"team": "home", "minute": 34},
            {"team": "home", "minute": 61},
            {"team": "home", "minute": 91},
            {"team": "away", "minute": 74},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Brentford",
        "away": "Liverpool",
        "round": 9,
        "stats": {
            "home_corners": 5,
            "away_corners": 4,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 17,
            "away_shots": 18,
            "home_shots_on_target": 8,
            "away_shots_on_target": 5,
            "home_xg": 3.27,
            "away_xg": 2.12,
        },
        "goals": [
            {"team": "home", "minute": 5},
            {"team": "home", "minute": 45},
            {"team": "home", "minute": 60},
            {"team": "away", "minute": 45},
            {"team": "away", "minute": 89},
        ],
    },
    {
        "home": "Arsenal",
        "away": "Crystal Palace",
        "round": 9,
        "stats": {
            "home_corners": 4,
            "away_corners": 3,
            "home_yellow_cards": 0,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 10,
            "away_shots": 7,
            "home_shots_on_target": 3,
            "away_shots_on_target": 1,
            "home_xg": 0.86,
            "away_xg": 0.35,
        },
        "goals": [
            {"team": "home", "minute": 39},
        ],
    },
    {
        "home": "Aston Villa",
        "away": "Manchester City",
        "round": 9,
        "stats": {
            "home_corners": 5,
            "away_corners": 6,
            "home_yellow_cards": 1,
            "away_yellow_cards": 4,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 18,
            "home_shots_on_target": 3,
            "away_shots_on_target": 4,
            "home_xg": 0.84,
            "away_xg": 1.37,
        },
        "goals": [
            {"team": "home", "minute": 19},
        ],
    },
    {
        "home": "Bournemouth",
        "away": "Nottingham Forest",
        "round": 9,
        "stats": {
            "home_corners": 6,
            "away_corners": 4,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 13,
            "away_shots": 8,
            "home_shots_on_target": 5,
            "away_shots_on_target": 4,
            "home_xg": 0.66,
            "away_xg": 0.31,
        },
        "goals": [
            {"team": "home", "minute": 25},
            {"team": "home", "minute": 40},
        ],
    },
    {
        "home": "Wolverhampton Wanderers",
        "away": "Burnley",
        "round": 9,
        "stats": {
            "home_corners": 4,
            "away_corners": 3,
            "home_yellow_cards": 1,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 15,
            "away_shots": 11,
            "home_shots_on_target": 7,
            "away_shots_on_target": 7,
            "home_xg": 2.58,
            "away_xg": 1.55,
        },
        "goals": [
            {"team": "home", "minute": 42},
            {"team": "home", "minute": 45},
            {"team": "away", "minute": 14},
            {"team": "away", "minute": 30},
            {"team": "away", "minute": 90},
        ],
    },
    {
        "home": "Everton",
        "away": "Tottenham Hotspur",
        "round": 9,
        "stats": {
            "home_corners": 9,
            "away_corners": 8,
            "home_yellow_cards": 2,
            "away_yellow_cards": 0,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 12,
            "away_shots": 7,
            "home_shots_on_target": 2,
            "away_shots_on_target": 4,
            "home_xg": 1.40,
            "away_xg": 2.09,
        },
        "goals": [
            {"team": "away", "minute": 19},
            {"team": "away", "minute": 45},
            {"team": "away", "minute": 89},
        ],
    },
    #ROUND 10
    {
        "home": "Fulham",
        "away": "Wolverhampton Wanderers",
        "round": 10,
        "stats": {
            "home_corners": 10,
            "away_corners": 1,
            "home_yellow_cards": 1,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 1,
            "home_shots": 19,
            "away_shots": 5,
            "home_shots_on_target": 6,
            "away_shots_on_target": 2,
            "home_xg": 1.91,
            "away_xg": 0.21,
        },
        "goals": [
            {"team": "home", "minute": 9},
            {"team": "home", "minute": 62},
            {"team": "home", "minute": 75},
        ],
    },
    {
        "home": "Burnley",
        "away": "Arsenal",
        "round": 10,
        "stats": {
            "home_corners": 1,
            "away_corners": 6,
            "home_yellow_cards": 2,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 3,
            "away_shots": 12,
            "home_shots_on_target": 0,
            "away_shots_on_target": 8,
            "home_xg": 0.68,
            "away_xg": 2.52,
        },
        "goals": [
            {"team": "away", "minute": 14},
            {"team": "away", "minute": 35},
        ],
    },
    {
        "home": "Brighton",
        "away": "Leeds United",
        "round": 10,
        "stats": {
            "home_corners": 4,
            "away_corners": 7,
            "home_yellow_cards": 0,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 14,
            "away_shots": 5,
            "home_shots_on_target": 7,
            "away_shots_on_target": 2,
            "home_xg": 2.64,
            "away_xg": 0.36,
        },
        "goals": [
            {"team": "home", "minute": 11},
            {"team": "home", "minute": 64},
            {"team": "home", "minute": 70},
        ],
    },
    {
        "home": "Nottingham Forest",
        "away": "Manchester United",
        "round": 10,
        "stats": {
            "home_corners": 8,
            "away_corners": 5,
            "home_yellow_cards": 1,
            "away_yellow_cards": 1,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 17,
            "away_shots": 18,
            "home_shots_on_target": 3,
            "away_shots_on_target": 7,
            "home_xg": 1.55,
            "away_xg": 0.92,
        },
        "goals": [
            {"team": "home", "minute": 48},
            {"team": "home", "minute": 50},
            {"team": "away", "minute": 34},
            {"team": "away", "minute": 81},
        ],
    },
    {
        "home": "Crystal Palace",
        "away": "Brentford",
        "round": 10,
        "stats": {
            "home_corners": 6,
            "away_corners": 5,
            "home_yellow_cards": 0,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 9,
            "away_shots": 6,
            "home_shots_on_target": 2,
            "away_shots_on_target": 2,
            "home_xg": 0.73,
            "away_xg": 0.82,
        },
        "goals": [
            {"team": "home", "minute": 30},
            {"team": "home", "minute": 51},
        ],
    },
    {
        "home": "Liverpool",
        "away": "Aston Villa",
        "round": 10,
        "stats": {
            "home_corners": 1,
            "away_corners": 4,
            "home_yellow_cards": 2,
            "away_yellow_cards": 3,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 16,
            "away_shots": 10,
            "home_shots_on_target": 4,
            "away_shots_on_target": 3,
            "home_xg": 1.47,
            "away_xg": 0.44,
        },
        "goals": [
            {"team": "home", "minute": 45},
            {"team": "home", "minute": 58},
        ],
    },
    {
        "home": "Manchester City",
        "away": "Bournemouth",
        "round": 10,
        "stats": {
            "home_corners": 9,
            "away_corners": 4,
            "home_yellow_cards": 2,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 15,
            "away_shots": 8,
            "home_shots_on_target": 8,
            "away_shots_on_target": 5,
            "home_xg": 2.49,
            "away_xg": 0.90,
        },
        "goals": [
            {"team": "home", "minute": 17},
            {"team": "home", "minute": 33},
            {"team": "home", "minute": 60},
            {"team": "away", "minute": 25},
        ],
    },
    {
        "home": "Sunderland",
        "away": "Everton",
        "round": 10,
        "stats": {
            "home_corners": 4,
            "away_corners": 1,
            "home_yellow_cards": 3,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 17,
            "away_shots": 8,
            "home_shots_on_target": 3,
            "away_shots_on_target": 2,
            "home_xg": 1.18,
            "away_xg": 1.01,
        },
        "goals": [
            {"team": "home", "minute": 46},
            {"team": "away", "minute": 15},
        ],
    },
    {
        "home": "Tottenham Hotspur",
        "away": "Chelsea",
        "round": 10,
        "stats": {
            "home_corners": 6,
            "away_corners": 5,
            "home_yellow_cards": 4,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 3,
            "away_shots": 15,
            "home_shots_on_target": 1,
            "away_shots_on_target": 9,
            "home_xg": 0.15,
            "away_xg": 3.34,
        },
        "goals": [
            {"team": "away", "minute": 34},
        ],
    },
    {
        "home": "West Ham United",
        "away": "Newcastle United",
        "round": 10,
        "stats": {
            "home_corners": 7,
            "away_corners": 6,
            "home_yellow_cards": 1,
            "away_yellow_cards": 2,
            "home_red_cards": 0,
            "away_red_cards": 0,
            "home_shots": 15,
            "away_shots": 12,
            "home_shots_on_target": 9,
            "away_shots_on_target": 4,
            "home_xg": 1.41,
            "away_xg": 0.52,
        },
        "goals": [
            {"team": "home", "minute": 35},
            {"team": "home", "minute": 45},
            {"team": "home", "minute": 90},
            {"team": "away", "minute": 4},
        ],
    }
]
