SEASON_2025_26 = [
    {
        "round": 1,
        "date": "2025-08-15 15:00",
        "matches": [
            ("Leeds United", "Everton"),
            ("Manchester United", "Arsenal"),
            ("Nottingham Forest", "Brentford"),
            ("Chelsea", "Crystal Palace"),
            ("Wolverhampton Wanderers", "Manchester City"),
            ("Brighton", "Fulham"),
            ("Sunderland", "West Ham United"),
            ("Tottenham Hotspur", "Burnley"),
            ("Aston Villa", "Newcastle United"),
            ("Liverpool", "Bournemouth"),
        ],
    },
    {
        "round": 2,
        "date": "2025-08-23 15:00",
        "matches": [
            ("West Ham United", "Chelsea"),
            ("Manchester City", "Tottenham Hotspur"),
            ("Bournemouth", "Wolverhampton Wanderers"),
            ("Brentford", "Aston Villa"),
            ("Burnley", "Sunderland"),
            ("Crystal Palace", "Nottingham Forest"),
            ("Everton", "Brighton"),
            ("Fulham", "Manchester United"),
            ("Newcastle United", "Liverpool"),
            ("Arsenal", "Leeds United"),
        ],
    },
    {
        "round": 3,
        "date": "2025-08-30 15:00",
        "matches": [
            ("Aston Villa", "Crystal Palace"),
            ("Chelsea", "Fulham"),
            ("Leeds United", "Newcastle United"),
            ("Liverpool", "Arsenal"),
            ("Manchester United", "Burnley"),
            ("Nottingham Forest", "West Ham United"),
            ("Sunderland", "Brentford"),
            ("Tottenham Hotspur", "Bournemouth"),
            ("Wolverhampton Wanderers", "Everton"),
            ("Brighton", "Manchester City"),
        ],
    },
    {
        "round": 4,
        "date": "2025-09-13 15:00",
        "matches": [
            ("Arsenal", "Nottingham Forest"),
            ("Bournemouth", "Brighton"),
            ("Brentford", "Chelsea"),
            ("Burnley", "Liverpool"),
            ("Crystal Palace", "Sunderland"),
            ("Everton", "Aston Villa"),
            ("Fulham", "Leeds United"),
            ("Manchester City", "Manchester United"),
            ("Newcastle United", "Wolverhampton Wanderers"),
            ("West Ham United", "Tottenham Hotspur"),
        ],
    },
    {
        "round": 5,
        "date": "2025-09-20 15:00",
        "matches": [
            ("Liverpool", "Everton"),
            ("Brighton", "Tottenham Hotspur"),
            ("Burnley", "Nottingham Forest"),
            ("West Ham United", "Crystal Palace"),
            ("Wolverhampton Wanderers", "Leeds United"),
            ("Manchester United", "Chelsea"),
            ("Fulham", "Brentford"),
            ("Bournemouth", "Newcastle United"),
            ("Sunderland", "Aston Villa"),
            ("Arsenal", "Manchester City"),
        ],
    },
    {
        "round": 6,
        "date": "2025-09-27 15:00",
        "matches": [
            ("Aston Villa", "Fulham"),
            ("Brentford", "Manchester United"),
            ("Crystal Palace", "Liverpool"),
            ("Leeds United", "Bournemouth"),
            ("Manchester City", "Burnley"),
            ("Newcastle United", "Arsenal"),
            ("Nottingham Forest", "Sunderland"),
            ("Tottenham Hotspur", "Wolverhampton Wanderers"),
            ("Everton", "West Ham United"),
            ("Chelsea", "Brighton"),
        ],
    },
    {
        "round": 7,
        "date": "2025-10-04 15:00",
        "matches": [
            ("Bournemouth", "Fulham"),
            ("Leeds United", "Tottenham Hotspur"),
            ("Arsenal", "West Ham United"),
            ("Manchester United", "Sunderland"),
            ("Chelsea", "Liverpool"),
            ("Everton", "Crystal Palace"),
            ("Aston Villa", "Burnley"),
            ("Newcastle United", "Nottingham Forest"),
            ("Wolverhampton Wanderers", "Brighton"),
            ("Brentford", "Manchester City"),
        ],
    },
    {
        "round": 8,
        "date": "2025-10-18 15:00",
        "matches": [
            ("Nottingham Forest", "Chelsea"),
            ("Brighton", "Newcastle United"),
            ("Burnley", "Leeds United"),
            ("West Ham United", "Brentford"),
            ("Fulham", "Arsenal"),
            ("Liverpool", "Manchester United"),
            ("Crystal Palace", "Bournemouth"),
            ("Manchester City", "Everton"),
            ("Sunderland", "Wolverhampton Wanderers"),
            ("Tottenham Hotspur", "Aston Villa"),
        ],
    },
    {
        "round": 9,
        "date": "2025-10-25 15:00",
        "matches": [
            ("Leeds United", "West Ham United"),
            ("Chelsea", "Sunderland"),
            ("Newcastle United", "Fulham"),
            ("Manchester United", "Brighton"),
            ("Brentford", "Liverpool"),
            ("Arsenal", "Crystal Palace"),
            ("Aston Villa", "Manchester City"),
            ("Bournemouth", "Nottingham Forest"),
            ("Wolverhampton Wanderers", "Burnley"),
            ("Everton", "Tottenham Hotspur"),
        ],
    },
    {
        "round": 10,
        "date": "2025-11-01 15:00",
        "matches": [
            ("Fulham", "Wolverhampton Wanderers"),
            ("Burnley", "Arsenal"),
            ("Brighton", "Leeds United"),
            ("Nottingham Forest", "Manchester United"),
            ("Crystal Palace", "Brentford"),
            ("Liverpool", "Aston Villa"),
            ("Manchester City", "Bournemouth"),
            ("Sunderland", "Everton"),
            ("Tottenham Hotspur", "Chelsea"),
            ("West Ham United", "Newcastle United"),
        ],
    },
]
